language: node_js

matrix:
  include:
    - node_js: "0.12"
    - node_js: "4.2"

sudo: require

before_install:
  - npm install -g grunt-cli babel mocha jshint

install:
  - npm install --unsafe-perm
  - npm install
