language: node_js

matrix:
  include:
    - node_js: "0.12"
      env:
        - CC="" CXX=""
    - node_js: "4.2"
      env:
        - CC="/usr/bin/gcc-4.8" CXX="/usr/bin/g++-4.8"

sudo: require

before_install:
  - sudo rm /etc/apt/sources.list.d/*.list
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libudev-dev libdbus-1-dev libdbus-glib-1-dev libglib2.0-dev libical-dev libreadline-dev g++-4.8
  - npm install -g grunt-cli babel mocha jshint

install:
  - npm install --unsafe-perm
  - npm install
