language: node_js

matrix:
  include:
    - node_js: "0.12"
    - node_js: "4.3"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: require

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install --unsafe-perm
  - npm install

notifications:
  slack:
    secure: OSy2j0wEVPnvA+4thx4SmG8m8/qw4u4JqJQGc1jIFnk5azAYH0gj5u2QQ2liSSk5Ezu7OiDvb1Pl9uNmzgbjqHA9saHVEaRVMZMf5hRJZkld6qB3urkmrAsTJdQy4B1V8I76++rWdPwyWGX0T12BMlVIMFmqIrcYp4F3Q7p9S7f7/7g3TNi1xX9JeHQLf4PhT/Jd3cjucbXSaabGGdilYbfDJA/hHUw4rIJ8y09JejOBh++grDFLte3kTW/M3hHIMMJbfqM+8n/pUvZpvLhSpw5OdGeYBlmA6QNOcNW4CeGnMMnlGx12lIPK2ewTDm8xfUx1MP36g2hIeYhMapJ6HZh/kq5GlgKnRz0qhM6z962VdVx5391eBVCatQ2c6e+1LG8Xf9LyoD6QjO31CsMtYRIzZ7ijdFDPyy29lxXPrO8BxM5Bef8XMEotG4fwIOE3qL6fOgOr8V7g8/89Rt4x/3ULuUvePVTI4nztWNtwVnb1V+zF4jkR+pReEwaOZV2Y6rFeJZUgx4YocjKhWJ2ijNTpLbxh6GTa70hzF//LWSlR4cbm8UHGAjxaUz3f1tLb+HTYGg385sk9268yVwmsmUTXoKKCWB9vYmbds8OLmrRQzK4tsZ8YWX6tzXPY/JQAHo+1R+as9PO5TuHEwkTALb9w2tXQEiU0iEnXWZzkeKU=
