language: node_js
node_js:
  - "0.12"
install: "npm run setup"
script:
  - "npm run test"
before_install:
  - sudo rm /etc/apt/sources.list.d/*.list
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential libudev-dev
